### ISSUE TITLE
Problem in connect to remote stan server

### ISSUE THREAD

**Issue by nextel** [nats-io/go-nats-streaming#94] opened 2016-07-16 19:59 UTC
Hi, i am trying to connect go stan client to remote stan server and server tell me something like that 
" 2016/07/16 21:48:31 Can't connect: nats: no servers available for connection.
Make sure a NATS Streaming Server is running at: nats://10.0.1.60:4222
"

steps what i am do:
1. make file seed.conf who look like 
"
listen: 0.0.0.0:4222
http: 8222
 "

2 start  server with command:
"./nats-streaming-server -c seed.conf"
who tell me
"
[6763] 2016/07/16 22:52:05.256046 [INF] Starting nats-streaming-server[test-cluster] version 0.2.0
[6763] 2016/07/16 22:52:05.256521 [INF] Starting nats-server version 0.9.0.beta
[6763] 2016/07/16 22:52:05.256544 [INF] Starting http monitor on :8222
[6763] 2016/07/16 22:52:05.256643 [INF] Listening for client connections on 0.0.0.0:4222
"
3. I want to send message to server from other computer whith standart instruction on site
go run stan-pub.go -c "nats://10.0.1.60:4222" foo "msg one" 
and take a message : 
Make sure a NATS Streaming Server is running at: nats://10.0.1.60:4222

what am i doing wrong?

**Comment by kozlovic** [comment] 2016-07-16 20:28
If your excerpt is correct, I think the issue is that you are providing the wrong flag for the client. It should be `-s nats://10.0.1.60:4222`, not `-c`.

**Comment by kozlovic** [comment] 2016-07-16 20:29
The flag `-c` is for the cluster name, which if not provided defaults to `test-cluster` which is also the default cluster name used by the server.

**Comment by nextel** [comment] 2016-07-17 06:43
Yea, u are right, but i am change -c to -s and nothing changed.  telnet 10.0.1.60 4222 -works and shows me  information aboout server in JSON but if i try to onnect to server from client, get  the same error and that at the beginning of.

**Comment by EduardFazliev** [comment] 2016-07-17 10:47
I have the same problem with NATS-streaming-server.
I have Nats-streaming server running on debian jessie with default parameters. Telnet to 4222 port on that host gives me json with server parameters and server log shows me parse error. But when I use stan-pob.go from go-nats-streamgin/examples:
    go run stan-pub.go -s nats://10.0.1.59:4222 foo "bar" 
it gives me error:
     Can't connect: EOF.
     Make sure a NATS Streaming Server is running at: nats://10.0.1.59:4222
     exit status 1
And server log doesn't show anything. If I will run stan-pub.go from server, where nats-streaming-server is running - command will succeed. Please help. You guys created really great thing and I want to use it, but for now I can't send messages to remote server. :(

**Comment by kozlovic** [comment] 2016-07-17 15:33
Guys, many apologies for the bad experience you got there. The examples are indeed wrong since we get the URL but don't use it at all so it would work only local. I will fix that asap. Again, sorry for the experience.

**Comment by kozlovic** [comment] 2016-07-17 16:05
Thanks @nextel and @EduardFazliev for reporting this issue. I have a PR up that will fix that. It will probably be merged tomorrow and we may also issue a new release to include this and few other issues and option setters that were added since `v.0.1.0`.

In the meantime, if you don't want to wait, you can work from this branch: https://github.com/nats-io/go-nats-streaming/tree/add_nats_url_option_setter

Thanks again!

**Comment by EduardFazliev** [comment] 2016-07-17 16:14
@kozlovic Thanks a lot! That was really fast bugfix :+1:  Great news!

**Comment by EduardFazliev** [comment] 2016-07-17 16:29
@kozlovic After checkout your branch and executing:
go run stan-pub.go --server nats://some.my.ip:4222 foo "bar"
I have error:

    # command-line-arguments
    ./stan-pub.go:58: undefined: stan.NatsURL

**Comment by EduardFazliev** [comment] 2016-07-17 16:40
@kozlovic Ignore my previous comment, I forgot to checkout to your branch in src :( silly me!

**Comment by kozlovic** [comment] 2016-07-17 16:41
@EduardFazliev Good, I was about to write that I could not reproduce this (removed repo, clone, checkout branch, worked fine).

**Comment by EduardFazliev** [comment] 2016-07-17 17:31
Now message sent is working, but after 10-20 sec I am getting error:
    nats://localhost:4222 clusterID: [test-cluster] clientID: [smth-pub_249]

But I am not using localhost, I am using IP for connection creation.

**Comment by kozlovic** [comment] 2016-07-17 18:34
Getting error where? On the server or the pub application? Publisher exits after sending message, so I don't think it can be in the pub. Any log you could provide? In what you report above, I don't see any actual error, just info about URL, cluster ID and client ID.

**Comment by nextel** [comment] 2016-07-18 14:54
And nwo one problem,  i have a code like in archive
[main.go.zip](https://github.com/nats-io/go-nats-streaming/files/369332/main.go.zip)


but it tells me some thing like this

:!
!!!
panic: too many subscriptions per channel

I need more doc, what subscriptions  It has
 mean.
It working with only one thread and only one subscriber.
I am feeling myself like a stuped newbie (((

**Comment by kozlovic** [comment] 2016-07-18 15:42
@nextel This is because by there is a limit (configurable) on the number of channels (subjects), subscriptions and messages per channel.
Things that could help:
http://nats.io/documentation/streaming/nats-streaming-intro/
https://github.com/nats-io/nats-streaming-server/blob/master/README.md
Also, `nats-streaming-server -h` will list the name of the parameters limiting the number of channels, messags, etc..
Let me know if this helps.

**Comment by kozlovic** [comment] 2016-07-18 15:44
.. and to answer specifically your question, the error you get is about reaching the max number of subscriptions on the subject you are using. Store limits defaults are:
```

**Closed** 2016-07-19 16:36 UTC
Labels: waffle:needs review
