### ISSUE TITLE
Support for connection pool

### ISSUE THREAD

**Issue by molon** [nats-io/go-nats-streaming#229] opened 2019-03-18 13:53 UTC
```
stan.Connect(clusterID, clientID, stan.NatsURL(URL),
		stan.SetConnectionLostHandler(func(_ stan.Conn, reason error) {
			log.Printf("Connection lost, reason: %v", reason)
		}),
		stan.Pings(1, 3),
	)
```
The `Connect` method is a blocking method and it must be recreate myself when `ConnectionLost`.
It's not convenient.

Maybe provide a pool like `github.com/gomodule/redigo` is a good choice.
Most of the time we want to run normally without a available `stan.Conn` and just returns err when called `Publish`.

Or provide a usage like `gRPC` (non-blocking Dial/auto-reconnect or others...)

**Comment by kozlovic** [comment] 2019-03-18 18:13
@molon The problem when a connection is lost is not really to recreate the connection. The library could have possibly done that, but the issue is with subscriptions.

Note that in NATS Streaming, a connection needs to provide a `clientID` that needs to be unique at a given time, that is, the server will reject a connection request with clientID `foo` if one is already connected with that ID. So having a pool of "ready" connections is not possible since it would not be possible to create more than one connection with the same ID.

If you are only publishing, you could simply call the same `stan.Connect()` call from the connection lost handler.

**Comment by molon** [comment] 2019-03-18 19:41
@kozlovic 
Thanks for reply.

The illusion is that the conn will be closed without `NatsConn`
https://github.com/nats-io/go-nats-streaming/blob/4366d43a0648b4997ed32080f937e8702ab86c48/stan.go#L464-L468

In any case, the conn is already stale after triggering `ConnectionLostHandler`.
It's `nc` is nil, `hbSubscription/pingSub/ackSubscription` are all unsubscribed.
It can no longer be used.
https://github.com/nats-io/go-nats-streaming/blob/4366d43a0648b4997ed32080f937e8702ab86c48/stan.go#L495-L505

Maybe need a demo for auto reactive for the `stan.Conn`.

**Comment by kozlovic** [comment] 2019-03-18 20:01
@molon Yes, if the STAN connection is lost, the library will unsubscribe all internal subscriptions that it uses if it does not own the NATS connection (if it owns it, simply closing it will implicitly unsubscribe them).

**Comment by kozlovic** [comment] 2019-03-22 22:36
Closing for now.. let me know if this need to be re-opened.

**Closed by kozlovic** 2019-03-22 22:36 UTC

**Comment by molon** [comment] 2019-03-23 06:50
Sorry about my poor english.
Maybe I don't quite understand what you said before.
I still don't know the best practices when the connection is lost.
I still don't know what to do to ensure that `stan.Conn` is always available after the `nats.Conn` is reconnected.

Could you provide a demo code for this please?

**Comment by kozlovic** [comment] 2019-03-25 15:03
@molon No worries. Here is an example on how to set a connection lost handler: https://github.com/nats-io/go-nats-streaming/blob/master/examples/stan-sub/main.go#L102

In this example, the application simply logs and exit. In your application, you would have to re-create a stan connection and subscriptions (if your application has some).

You should really have a look at this: https://github.com/nats-io/go-nats-streaming#connection-status. It will explain all the details. The point is, if you setup the connection lost handler, your application will be notified if the STAN connection is deemed permanently lost. Having a `nats.Conn` temporarily disconnected should not be the concern of your application. If it can reconnect, you have nothing to do. If it is permanently closed, the mentioned callback will be invoked to let you know that the STAN connection is lost.

**Comment by molon** [comment] 2019-03-25 18:43
> In this example, the application simply logs and exit. In your application, you would have to re-create a stan connection and subscriptions (if your application has some).

Thx, I see. 
Having to reconnect completely. Although it's not very graceful.

**Comment by lambdaxs** [comment] 2020-02-06 12:44
> > 在此示例中，应用程序仅记录并退出。在您的应用程序中，您将必须重新创建一个stan连接和订阅（如果您的应用程序中有一些）。
> 
> 谢谢，我明白了。
> 必须完全重新连接。虽然不是很优雅。

Hello，I wrote a library to solve this problem：
 https://github.com/lambdaxs/stan.reconnect
😊
