### ISSUE TITLE
Subscribe using StartAtTime triggering latest result even if before start time

### ISSUE THREAD

**Issue by kmhagan** [nats-io/go-nats-streaming#203] opened 2018-09-27 23:51 UTC
Hello,

Not sure if this is because of the client or the server but when I subscribe to a topic with the option to start at a specific time it will return the latest result even if it is before the start time. I would expect for no results to be returned.

Here is a code sample:
```
package main

import (
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/nats-io/go-nats-streaming"
)

func main() {
	natsUsername := os.Getenv("NATS_USERNAME")
	natsPassword := os.Getenv("NATS_PASSWORD")
	natsURL := os.Getenv("NATS_URL")
	natsServer := "nats://" + natsUsername + ":" + natsPassword + "@" + natsURL
	hostname, _ := os.Hostname()

	sc, _ := stan.Connect("cluster", hostname, stan.NatsURL(natsServer))
	sc.Publish("test", []byte(fmt.Sprintf("Time of this message was %s", time.Now())))

	time.Sleep(10 * time.Second)
	startTime := time.Now()
	time.Sleep(5 * time.Second)

	fmt.Printf("The start time for the subscribe is: %s\n", startTime)
	sc.Subscribe("test", func(m *stan.Msg) {
		fmt.Printf("Msg received on [%s] at %s: %s\n", m.Subject, time.Now(), string(m.Data))
	}, stan.StartAtTime(startTime))

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello world!\n")
	})
	http.ListenAndServe(":8080", nil)
}
```

And here is the output:
```
The start time for the subscribe is: 2018-09-27 23:31:18.333744006 +0000 UTC m=+10.024165528
Msg received on [test] at 2018-09-27 23:31:23.336176964 +0000 UTC m=+15.026598492: Time of this message was 2018-09-27 23:31:08.331829487 +0000 UTC m=+0.022251017
```

**Comment by kozlovic** [comment] 2018-09-28 00:07
Which version of server and client are you using? I am not able to reproduce this with latest.

**Comment by kozlovic** [comment] 2018-09-28 00:08
Please run the server with `-SDV` and send me the output of your running your test against it. Thanks!

**Comment by kmhagan** [comment] 2018-09-28 00:14
The server I am running 0.10.2 and the client is pulling the latest.

When I get a chance (hopefully tomorrow) I'll upgrade the server and see if that fixes it. If you like I can run with -SDV before I upgrade.

Thanks for the help!

**Comment by kozlovic** [comment] 2018-09-28 00:15
Yes, please run the test with -SDV before upgrade. I don't think that there is any change in latest vs 0.10.2 that would explain the difference.

**Comment by kmhagan** [comment] 2018-09-28 00:57
Here are the server logs with -SDV, I am running a three node cluster:

```
[1] 2018/09/28 00:50:02.520423 [DBG] STREAM: [Client:test-5dc4dfc867-948h2] Connected (Inbox=_INBOX.Bye6EjVKRLSbgnLATwo6QB)
[1] 2018/09/28 00:50:02.521378 [INF] STREAM: Channel "test" has been created
[1] 2018/09/28 00:50:02.522045 [TRC] STREAM: [Client:test-5dc4dfc867-948h2] Acking Publisher subj=test guid=V56Fb4ciyq85odwHtZwLbI
[1] 2018/09/28 00:50:17.523859 [DBG] STREAM: [Client:test-5dc4dfc867-948h2] Started new subscription, subject=test, inbox=_INBOX.Bye6EjVKRLSbgnLATwo6aV, subid=1, sending from sequence, asked_seq=1 actual_seq=1
[1] 2018/09/28 00:50:17.523922 [TRC] STREAM: [Client:test-5dc4dfc867-948h2] Delivering msg to subid=1, subject=test, seq=1
[1] 2018/09/28 00:50:17.524619 [TRC] STREAM: [Client:test-5dc4dfc867-948h2] Processing ack for subid=1, subject=test, seq=1
```

```
[1] 2018/09/28 00:50:02.521435 [DBG] STREAM: [Client:test-5dc4dfc867-948h2] Connected (Inbox=_INBOX.Bye6EjVKRLSbgnLATwo6QB)
[1] 2018/09/28 00:50:02.578199 [INF] STREAM: Channel "test" has been created
[1] 2018/09/28 00:50:17.605333 [DBG] STREAM: [Client:test-5dc4dfc867-948h2] Started new subscription, subject=test, inbox=_INBOX.Bye6EjVKRLSbgnLATwo6aV, subid=1, sending from sequence, asked_seq=1 actual_seq=1
```

```
[1] 2018/09/28 00:50:02.522727 [DBG] STREAM: [Client:test-5dc4dfc867-948h2] Connected (Inbox=_INBOX.Bye6EjVKRLSbgnLATwo6QB)
[1] 2018/09/28 00:50:02.582879 [INF] STREAM: Channel "test" has been created
[1] 2018/09/28 00:50:17.610297 [DBG] STREAM: [Client:test-5dc4dfc867-948h2] Started new subscription, subject=test, inbox=_INBOX.Bye6EjVKRLSbgnLATwo6aV, subid=1, sending from sequence, asked_seq=1 actual_seq=1
```

**Comment by kozlovic** [comment] 2018-09-28 00:58
Thanks, I was not testing in clustering mode. Will have a look.

**Comment by kozlovic** [comment] 2018-09-28 01:07
Ok, I have created a test with clustering mode and indeed it fails. Will work on a fix. Thank you for the report!

**Comment by kozlovic** [comment] 2018-09-28 15:31
@kmhagan Thanks again for the report. This is indeed an issue with the server, not the client. I have created issue https://github.com/nats-io/nats-streaming-server/issues/657 in the server and have a PR that addresses the issue. I am closing this issue in the client repo and you can follow the one in the server. Thanks!

**Closed by kozlovic** 2018-09-28 15:31 UTC

**Comment by kmhagan** [comment] 2018-09-28 15:38
@kozlovic thanks for the support!
